### ISSUE TITLE
Gem dependency conflict

### ISSUE THREAD

**Issue by danapplegate** [winebarrel/fluent-plugin-kinesis-firehose#6]
Hi there,

I'm running into a gem dependency conflict when I try to use this plugin alongside the [`fluent-plugin-s3`](https://rubygems.org/gems/fluent-plugin-s3). It appears that fluent-plugin-kinesis-firehose requires `aws-sdk ~> 2.1.28`, which causes a conflict with the subsequently dependent `aws-sdk-resources` package from the s3 plugin's `aws-sdk ~> 2` dependency. Here's the exception I get during my Chef run:

```
---- Begin output of /etc/init.d/td-agent restart ----
           STDOUT: Restarting td-agent:  * td-agent
           STDERR: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate aws-sdk-2.1.36, because aws-sdk-resources-2.2.14 conflicts with aws-sdk-resources (= 2.1.36) (Gem::ConflictError)
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1300:in `each'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1300:in `activate_dependencies'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'

            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-firehose-0.1.1/lib/fluent/plugin/out_kinesis_firehose.rb:1:in `<top (required)>'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:168:in `block in try_load_plugin'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:166:in `each'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:166:in `try_load_plugin'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:126:in `new_impl'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:57:in `new_output'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:127:in `add_match'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:60:in `block in configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:54:in `each'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:54:in `configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:82:in `configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:117:in `configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:91:in `run_configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:515:in `run_configure'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:186:in `dry_run'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:133:in `start'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
            from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
            from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/bin/fluentd:6:in `<top (required)>'
            from /opt/td-agent/embedded/bin/fluentd:23:in `load'
            from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
            from /usr/sbin/td-agent:7:in `load'
            from /usr/sbin/td-agent:7:in `<main>'
           ---- End output of /etc/init.d/td-agent restart ----
       Ran /etc/init.d/td-agent restart returned 1
```

To reproduce:
1. Use base Ubuntu 12.04
2. `sudo apt-get update`
3. Install td-agent `sudo apt-get install td-agent`
4. Install both td-agent-gems: `sudo td-agent-gem install fluent-plugin-s3 fluent-plugin-kinesis-firehose`
5. Edit `/etc/td-agent/td-agent.conf` to include match blocks with both plugins

```
<match *>
    type s3
    aws_key_id ...
    aws_sec_key ...
    s3_bucket ...
    s3_region us-east-1
    time_slice_format %Y%m%d
    buffer_path /var/log/td-agent/s3-email
    path logs/app/email
    utc
</match>
<match *>
    type kinesis_firehose
    delivery_stream_name ...
    aws_key_id ...
    aws_sec_key ...
    region us-east-1
    append_new_line true
</match>
```
1. `sudo service td-agent restart`, which fails with the above error and stack trace

Any ideas on how to resolve this issue?

**Comment by riywo** [comment]
Hi,

If you want to send logs to Kinesis Firehose, you can also try to use `fluent-plugin-kinesis` v1.0.0.
https://github.com/awslabs/aws-fluent-plugin-kinesis

**Comment by bratislavml** [comment]
Hi it seems I have the same problem that danapplegate had, after plugin installation I am getting following error:

/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in raise_if_conflicts': Unable to activate aws-sdk-2.1.36, because aws-sdk-resources-2.2.3 conflicts with aws-sdk-resources (= 2.1.36) (Gem::LoadError) from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1262:inactivate'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1298:in block in activate_dependencies' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:ineach'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in activate_dependencies' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1266:inactivate'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in rescue in try_activate' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:intry_activate'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in rescue in require' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:inrequire'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-firehose-0.1.1/lib/fluent/plugin/out_kinesis_firehose.rb:1:in <top (required)>' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:inrequire'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in require' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:168:inblock in try_load_plugin'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:166:in each' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:166:intry_load_plugin'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:126:in new_impl' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:57:innew_output'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:41:in block in configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:34:ineach'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:34:in configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:129:inadd_match'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:60:in block in configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:54:ineach'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:54:in configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/root_agent.rb:82:inconfigure'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/engine.rb:116:in configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/engine.rb:90:inrun_configure'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:497:in run_configure' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:145:inblock in start'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:336:in call' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:336:inmain_process'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:311:in block in supervise' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:310:infork'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:310:in supervise' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:141:instart'
from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/command/fluentd.rb:171:in <top (required)>' from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:inrequire'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in require' from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/bin/fluentd:6:in'
from /opt/td-agent/embedded/bin/fluentd:23:in load' from /opt/td-agent/embedded/bin/fluentd:23:in'
from /usr/sbin/td-agent:7:in load' from /usr/sbin/td-agent:7:in

'
[FAILED]
2016-07-14 11:19:28 -0400 [info]: process finished code=256
2016-07-14 11:19:28 -0400 [warn]: process died within 1 second. exit.
^C[1]+ Exit 1 service td-agent start
This is td-agent version:

/etc/td-agent/conf.d]# yum info td-agent
Loaded plugins: priorities, update-motd, upgrade-helper
959 packages excluded due to repository priority protections
Installed Packages
Name : td-agent
Arch : x86_64
Version : 2.2.1
Release : 0.el2015
Size : 199 M
Repo : installed
From repo : treasuredata
Summary : Treasure Agent: A data collector for Treasure Data
URL : http://treasuredata.com
License : unknown
Description : Treasure Agent: A data collector for Treasure Data

Could you please help about this?

Thanks

**Comment by winebarrel** [comment]
Sorry, this plugin in is deprecated. 😢 
Please use [fluent-plugin-kinesis](https://github.com/awslabs/aws-fluent-plugin-kinesis).
